In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r'C:\Users\Welcome\Desktop\Data Science Internship\CSV FILES\forestcover.csv')
df

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0          1       2596      51      3                               258   
1          2       2590      56      2                               212   
2          3       2804     139      9                               268   
3          4       2785     155     18                               242   
4          5       2595      45      2                               153   
...      ...        ...     ...    ...                               ...   
15115  15116       2607     243     23                               258   
15116  15117       2603     121     19                               633   
15117  15118       2492     134     25                               365   
15118  15119       2487     167     28                               218   
15119  15120       2475     197     34                               319   

       Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                   0                              510   
1                                  -6                              390   
2                                  65                             3180   
3                                 118                             3090   
4                                  -1                              391   
...                               ...                              ...   
15115                               7                              660   
15116                             195                              618   
15117                             117                              335   
15118                             101                              242   
15119                              78                              270   

       Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type32  \
0                221             232            148  ...            0   
1                220             235            151  ...            0   
2                234             238            135  ...            0   
3                238             238            122  ...            0   
4                220             234            150  ...            0   
...              ...             ...            ...  ...          ...   
15115            170             251            214  ...            0   
15116            249             221             91  ...            0   
15117            250             220             83  ...            0   
15118            229             237            119  ...            0   
15119            189             244            164  ...            0   

       Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0                0            0            0            0            0   
1                0            0            0            0            0   
2                0            0            0            0            0   
3                0            0            0            0            0   
4                0            0            0            0            0   
...            ...          ...          ...          ...          ...   
15115            0            0            0            0            0   
15116            0            0            0            0            0   
15117            0            0            0            0            0   
15118            0            0            0            0            0   
15119            0            0            0            0            0   

       Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0                0            0            0           5  
1                0            0            0           5  
2                0            0            0           2  
3                0            0            0           2  
4                0            0            0           5  
...            ...          ...          ...         ...  
15115            0           

In [3]:
df.head(20)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0    1       2596      51      3                               258   
1    2       2590      56      2                               212   
2    3       2804     139      9                               268   
3    4       2785     155     18                               242   
4    5       2595      45      2                               153   
5    6       2579     132      6                               300   
6    7       2606      45      7                               270   
7    8       2605      49      4                               234   
8    9       2617      45      9                               240   
9   10       2612      59     10                               247   
10  11       2612     201      4                               180   
11  12       2886     151     11                               371   
12  13       2742     134     22                               150   
13  14       2609     214      7                               150   
14  15       2503     157      4                                67   
15  16       2495      51      7                                42   
16  17       2610     259      1                               120   
17  18       2517      72      7                                85   
18  19       2504       0      4                                95   
19  20       2503      38      5                                85   

    Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                0                              510   
1                               -6                              390   
2                               65                             3180   
3                              118                             3090   
4                               -1                              391   
5                              -15                               67   
6                                5                              633   
7                                7                              573   
8                               56                              666   
9                               11                              636   
10                              51                              735   
11                              26                             5253   
12                              69                             3215   
13                              46                              771   
14                               4                              674   
15                               2                              752   
16                              -1                              607   
17                               6                              595   
18                               5                              691   
19                              10                              741   

    Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type32  \
0             221             232            148  ...            0   
1             220             235            151  ...            0   
2             234             238            135  ...            0   
3             238             238            122  ...            0   
4             220             234            150  ...            0   
5             230             237            140  ...            0   
6             222             225            138  ...            0   
7             222             230            144  ...            0   
8             223             221            133  ...            0   
9             228             219            124  ...            0   
10            218             243            161  ...            0   
11            234             240            136  ...            0   
12            248             224             92  ...            0   
13            213             247            170  ...        

In [4]:
df.tail()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
15115  15116       2607     243     23                               258   
15116  15117       2603     121     19                               633   
15117  15118       2492     134     25                               365   
15118  15119       2487     167     28                               218   
15119  15120       2475     197     34                               319   

       Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
15115                               7                              660   
15116                             195                              618   
15117                             117                              335   
15118                             101                              242   
15119                              78                              270   

       Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type32  \
15115            170             251            214  ...            0   
15116            249             221             91  ...            0   
15117            250             220             83  ...            0   
15118            229             237            119  ...            0   
15119            189             244            164  ...            0   

       Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
15115            0            0            0            0            0   
15116            0            0            0            0            0   
15117            0            0            0            0            0   
15118            0            0            0            0            0   
15119            0            0            0            0            0   

       Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
15115            0            0            0           3  
15116            0            0            0           3  
15117            0            0            0           3  
15118            0            0            0           3  
15119            0            0            0           3  

[5 rows x 56 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  15120 non-null  int64
 1   Elevation                           15120 non-null  int64
 2   Aspect                              15120 non-null  int64
 3   Slope                               15120 non-null  int64
 4   Horizontal_Distance_To_Hydrology    15120 non-null  int64
 5   Vertical_Distance_To_Hydrology      15120 non-null  int64
 6   Horizontal_Distance_To_Roadways     15120 non-null  int64
 7   Hillshade_9am                       15120 non-null  int64
 8   Hillshade_Noon                      15120 non-null  int64
 9   Hillshade_3pm                       15120 non-null  int64
 10  Horizontal_Distance_To_Fire_Points  15120 non-null  int64
 11  Wilderness_Area1                    15120 non-null  int64
 12  Wild

In [6]:
df.isnull().sum()

Id                                    0
Elevation                             0
Aspect                                0
Slope                                 0
Horizontal_Distance_To_Hydrology      0
Vertical_Distance_To_Hydrology        0
Horizontal_Distance_To_Roadways       0
Hillshade_9am                         0
Hillshade_Noon                        0
Hillshade_3pm                         0
Horizontal_Distance_To_Fire_Points    0
Wilderness_Area1                      0
Wilderness_Area2                      0
Wilderness_Area3                      0
Wilderness_Area4                      0
Soil_Type1                            0
Soil_Type2                            0
Soil_Type3                            0
Soil_Type4                            0
Soil_Type5                            0
Soil_Type6                            0
Soil_Type7                            0
Soil_Type8                            0
Soil_Type9                            0
Soil_Type10                           0


In [7]:
df.duplicated().sum()

0

In [8]:
df.describe()

Id     Elevation        Aspect         Slope  \
count  15120.00000  15120.000000  15120.000000  15120.000000   
mean    7560.50000   2749.322553    156.676653     16.501587   
std     4364.91237    417.678187    110.085801      8.453927   
min        1.00000   1863.000000      0.000000      0.000000   
25%     3780.75000   2376.000000     65.000000     10.000000   
50%     7560.50000   2752.000000    126.000000     15.000000   
75%    11340.25000   3104.000000    261.000000     22.000000   
max    15120.00000   3849.000000    360.000000     52.000000   

       Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
count                      15120.000000                    15120.000000   
mean                         227.195701                       51.076521   
std                          210.075296                       61.239406   
min                            0.000000                     -146.000000   
25%                           67.000000                        5.000000   
50%                          180.000000                       32.000000   
75%                          330.000000                       79.000000   
max                         1343.000000                      554.000000   

       Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
count                     15120.000000   15120.000000    15120.000000   
mean                       1714.023214     212.704299      218.965608   
std                        1325.066358      30.561287       22.801966   
min                           0.000000       0.000000       99.000000   
25%                         764.000000     196.000000      207.000000   
50%                        1316.000000     220.000000      223.000000   
75%                        2270.000000     235.000000      235.000000   
max                        6890.000000     254.000000      254.000000   

       Hillshade_3pm  ...   Soil_Type32   Soil_Type33   Soil_Type34  \
count   15120.000000  ...  15120.000000  15120.000000  15120.000000   
mean      135.091997  ...      0.045635      0.040741      0.001455   
std        45.895189  ...      0.208699      0.197696      0.038118   
min         0.000000  ...      0.000000      0.000000      0.000000   
25%       106.000000  ...      0.000000      0.000000      0.000000   
50%       138.000000  ...      0.000000      0.000000      0.000000   
75%       167.000000  ...      0.000000      0.000000      0.000000   
max       248.000000  ...      1.000000      1.000000      1.000000   

        Soil_Type35   Soil_Type36   Soil_Type37   Soil_Type38   Soil_Type39  \
count  15120.000000  15120.000000  15120.000000  15120.000000  15120.000000   
mean       0.006746      0.000661      0.002249      0.048148      0.043452   
std        0.081859      0.025710      0.047368      0.214086      0.203880   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      0.000000      0.000000      0.000000   
50%        0.000000      0.000000      0.000000      0.000000      0.000000   
75%        0.000000      0.000000      0.000000      0.000000      0.000000   
max        1.000000      1.000000      1.000000      1.000000      1.000000   

        Soil_Type40    Cover_Type  
count  15120.000000  15120.000000  
mean       0.030357      4.000000  
std        0.171574      2.000066  
min        0.000000      1.000000  
25%        0.000000      2.000000  
50%        0.000000      4.000000  
75%        0.000000      6.000000  
max        1.000000      7.000000  

[8 rows x 56 columns]

In [9]:
dfa=df.copy()

In [10]:
dfa

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0          1       2596      51      3                               258   
1          2       2590      56      2                               212   
2          3       2804     139      9                               268   
3          4       2785     155     18                               242   
4          5       2595      45      2                               153   
...      ...        ...     ...    ...                               ...   
15115  15116       2607     243     23                               258   
15116  15117       2603     121     19                               633   
15117  15118       2492     134     25                               365   
15118  15119       2487     167     28                               218   
15119  15120       2475     197     34                               319   

       Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                   0                              510   
1                                  -6                              390   
2                                  65                             3180   
3                                 118                             3090   
4                                  -1                              391   
...                               ...                              ...   
15115                               7                              660   
15116                             195                              618   
15117                             117                              335   
15118                             101                              242   
15119                              78                              270   

       Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type32  \
0                221             232            148  ...            0   
1                220             235            151  ...            0   
2                234             238            135  ...            0   
3                238             238            122  ...            0   
4                220             234            150  ...            0   
...              ...             ...            ...  ...          ...   
15115            170             251            214  ...            0   
15116            249             221             91  ...            0   
15117            250             220             83  ...            0   
15118            229             237            119  ...            0   
15119            189             244            164  ...            0   

       Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0                0            0            0            0            0   
1                0            0            0            0            0   
2                0            0            0            0            0   
3                0            0            0            0            0   
4                0            0            0            0            0   
...            ...          ...          ...          ...          ...   
15115            0            0            0            0            0   
15116            0            0            0            0            0   
15117            0            0            0            0            0   
15118            0            0            0            0            0   
15119            0            0            0            0            0   

       Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0                0            0            0           5  
1                0            0            0           5  
2                0            0            0           2  
3                0            0            0           2  
4                0            0            0           5  
...            ...          ...          ...         ...  
15115            0           

# Model Building

In [11]:
from sklearn.model_selection import train_test_split

x=dfa.drop(columns='Cover_Type')
y=dfa['Cover_Type']

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.20, random_state=0)
print('x_train size: {}, x_test size: {}'.format(x_train.shape, x_test.shape))

x_train size: (12096, 55), x_test size: (3024, 55)


In [12]:
y

0        5
1        5
2        2
3        2
4        5
        ..
15115    3
15116    3
15117    3
15118    3
15119    3
Name: Cover_Type, Length: 15120, dtype: int64

# Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
x_train

array([[-0.03670473,  1.47745234,  1.24641777, ...,  4.32438732,
        -0.21279501, -0.17363233],
       [-0.59374422, -1.27154731, -0.42495364, ..., -0.23124663,
        -0.21279501, -0.17363233],
       [-0.40095812,  1.48944623,  0.9829951 , ..., -0.23124663,
        -0.21279501,  5.7592961 ],
       ...,
       [ 0.53156724,  1.83247149,  0.0110563 , ..., -0.23124663,
        -0.21279501, -0.17363233],
       [ 0.75025681, -0.42237988, -0.69745984, ..., -0.23124663,
        -0.21279501, -0.17363233],
       [-1.09897674, -0.03137906,  1.33725317, ..., -0.23124663,
        -0.21279501, -0.17363233]])

# Machine learning techniques

In [15]:
from sklearn.model_selection import ShuffleSplit
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report

In [16]:
# Initialize the logistic regression model
lg = LogisticRegression()
# Fit the model with training data
lg.fit(x_train, y_train)
# Predict the labels for the test set
ypred = lg.predict(x_test)
# Calculate the accuracy score
accuracy = accuracy_score(y_test, ypred)

print("Accuracy:",accuracy)

Accuracy: 0.701058201058201


In [17]:
# Initialize the decision Tree classifier
model_dt=DecisionTreeClassifier(random_state=42)

#train the model
model_dt.fit(x_train,y_train)

#Make predictions
y_pred_dt=model_dt.predict(x_test)

#calculate performance metrics
accuracy_dt=accuracy_score(y_test,y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt,average='weighted')
recall_dt = recall_score(y_test, y_pred_dt,average='weighted')
f1_dt = f1_score(y_test, y_pred_dt,average='weighted')
conf_matrix_dt=confusion_matrix(y_test,y_pred_dt)
class_report_dt=classification_report(y_test,y_pred_dt)

# print the performance metrics for Decision Tree
print('Decision Tree Metrics:')
print('Accuracy:',round(accuracy_dt,2))
print('Precision:',round(precision_dt,2))
print('Recall:',round(recall_dt,2))
print('F1-Score:',round(f1_dt,2))
print('Confusion Matrix:\n',conf_matrix_dt)
print('Classification Report:\n',class_report_dt)

Decision Tree Metrics:
Accuracy: 0.75
Precision: 0.75
Recall: 0.75
F1-Score: 0.75
Confusion Matrix:
 [[287  91   2   0   9   4  46]
 [ 95 235  17   0  52   6   6]
 [  0   4 304  28   7  75   0]
 [  0   0  22 400   0  16   0]
 [ 17  45  10   0 343  13   0]
 [  5  29  75  10  15 337   0]
 [ 42   3   0   0   0   0 374]]
Classification Report:
               precision    recall  f1-score   support

           1       0.64      0.65      0.65       439
           2       0.58      0.57      0.57       411
           3       0.71      0.73      0.72       418
           4       0.91      0.91      0.91       438
           5       0.81      0.80      0.80       428
           6       0.75      0.72      0.73       471
           7       0.88      0.89      0.89       419

    accuracy                           0.75      3024
   macro avg       0.75      0.75      0.75      3024
weighted avg       0.75      0.75      0.75      3024



In [33]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

model_rf.fit(x_train, y_train)

# Make predictions
y_pred_rf = model_rf.predict(x_test)

# Calculate performance metrics
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf,average='weighted')
recall_rf = recall_score(y_test, y_pred_rf,average='weighted')
f1_rf = f1_score(y_test, y_pred_rf,average='weighted')
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
class_report_rf = classification_report(y_test, y_pred_rf)

# Print the performance metrics for Random Forest
print('Random Forest Metrics:')
print('Accuracy:', round(accuracy_rf, 2))
print('Precision:', round(precision_rf, 2))
print('Recall:', round(recall_rf, 2))
print('F1-Score:', round(f1_rf, 2))
print('Confusion Matrix:\n', conf_matrix_rf)
print('Classification Report:\n', class_report_rf)

Random Forest Metrics:
Accuracy: 0.85
Precision: 0.85
Recall: 0.85
F1-Score: 0.85
Confusion Matrix:
 [[328  70   1   0   6   1  33]
 [ 74 287  13   0  26   6   5]
 [  0   1 353  22   6  36   0]
 [  0   0  12 422   0   4   0]
 [  0  25   6   0 394   3   0]
 [  0   1  62   9  10 389   0]
 [ 19   3   0   0   0   0 397]]
Classification Report:
               precision    recall  f1-score   support

           1       0.78      0.75      0.76       439
           2       0.74      0.70      0.72       411
           3       0.79      0.84      0.82       418
           4       0.93      0.96      0.95       438
           5       0.89      0.92      0.91       428
           6       0.89      0.83      0.85       471
           7       0.91      0.95      0.93       419

    accuracy                           0.85      3024
   macro avg       0.85      0.85      0.85      3024
weighted avg       0.85      0.85      0.85      3024



# Cross validation

In [19]:
from sklearn.model_selection import ShuffleSplit, cross_val_score
#initialize the decision tree model
model_dt=DecisionTreeClassifier(random_state=42)
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
#perform cross validation
results_dt= cross_val_score(model_dt,x,y,cv=ssplit)
#print results
print('Decision Tree Cross-validation:',results_dt)
print("\nMean Cross-validation Accuracy:",np.mean(results_dt))

Decision Tree Cross-validation: [0.77601411 0.78703704 0.78813933 0.78328924 0.7771164  0.78064374
 0.78240741 0.78593474 0.77336861 0.77138448]

Mean Cross-validation Accuracy: 0.7805335097001764


In [20]:
from sklearn.model_selection import ShuffleSplit, cross_val_score
#initialize the RandomForest model
model_rf=RandomForestClassifier(random_state=42)
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
#perform cross validation
results_rf= cross_val_score(model_rf,x,y,cv=ssplit)
#print results
print('Random Forest Cross-validation:',results_rf)
print("\nMean Cross-validation Accuracy:",np.mean(results_rf))

Random Forest Cross-validation: [0.86463845 0.86485891 0.8723545  0.85736332 0.86640212 0.875
 0.86816578 0.86199295 0.86816578 0.86419753]

Mean Cross-validation Accuracy: 0.8663139329805997


In [21]:
model=LogisticRegression()
ssplit=ShuffleSplit(n_splits=10,test_size=0.30)
from sklearn.model_selection import cross_val_score
results= cross_val_score(model,x,y,cv=ssplit)
print(results)
print("\nMean Cross-validation Accuracy:",np.mean(results))

[0.37786596 0.36882716 0.36067019 0.37720459 0.38646384 0.39109347
 0.39660494 0.38822751 0.38999118 0.38492063]

Mean Cross-validation Accuracy: 0.3821869488536155


# Prediction System

In [22]:
df.iloc[10].values

array([  11, 2612,  201,    4,  180,   51,  735,  218,  243,  161, 6222,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5], dtype=int64)

In [23]:
df.iloc[5].values

array([   6, 2579,  132,    6,  300,  -15,   67,  230,  237,  140, 6031,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          2], dtype=int64)

In [24]:
input_values = (200, 2998,   45,    8,  351,   16, 5842,  223,  222,  134, 3721,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0)

In [31]:
import numpy as np
features = np.array([input_values])

In [34]:
model_rf.predict(features).reshape(1,-1)

array([[1]], dtype=int64)

In [35]:
import pickle
pickle.dump(model_rf,open('model_rf.pkl','wb'))
print("Model saved successfully.")

Model saved successfully.


In [36]:

streamlit_code ="""
import streamlit as st
import pickle
import numpy as np
from PIL import Image

model_rf = pickle.load(open('model_rf.pkl', 'rb'))

# Creating web app
st.title('Forest Cover Type Prediction')
#image = Image.open('img.png')
#st.image(image, caption='myimage', use_column_width=True)
user_input = st.text_input('Input Features')

if user_input:
    user_input = user_input.split(',')
    features = np.array([user_input], dtype=np.float64)
    output = model_rf.predict(features).reshape(1, -1)

    # Create the cover type dictionary
    cover_type_dict = {
        1: {"name": "Spruce/Fir", "image": "img_1.jpg"},
        2: {"name": "Lodgepole Pine", "image": "img_2.png"},
        3: {"name": "Ponderosa Pine", "image": "img_3.png"},
        4: {"name": "Cottonwood/Willow", "image": "img_4.jpg"},
        5: {"name": "Aspen", "image": "img_5.jpg"},
        6: {"name": "Douglas-fir", "image": "img_6.png"},
        7: {"name": "Krummholz", "image": "img_7.png"}
    }

    # Convert the output to integer
    predicted_cover_type = int(output[0])
    cover_type_info = cover_type_dict.get(predicted_cover_type)

    if cover_type_info is not None:
        cover_type_name = cover_type_info["name"]
        cover_type_image_path = cover_type_info["image"]

        # Display the cover type card
        col1, col2 = st.columns([2, 3])

        with col1:
            st.write("Predicted Cover Type:")
            st.write(f"<h1 style='font-size: 40px; font-weight: bold;'>{cover_type_name}</h1>", unsafe_allow_html=True)

        with col2:
            cover_type_image = Image.open(cover_type_image_path)
            st.image(cover_type_image, caption=cover_type_name, use_column_width=True)
    else:
        st.write("Unable to make a prediction")
"""
# Specify the file path where the fcoverapp.py file will be saved
file_path = 'fcoverapp.py'

# Write the content to the file
with open(file_path, 'w') as file:
    file.write(streamlit_code)

print(f"File '{file_path}' has been saved.")


File 'fcoverapp.py' has been saved.
